version: '3'
services:
  backend:
    build:
      context: ./backend
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - FRONTEND_HOST=${FRONTEND_HOST}
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  frontend:
    build:
      context: ./frontend
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - NODE_ENV=${NODE_ENV}
        - API_ENV=${API_ENV}
        - BACKEND_HOST=${BACKEND_HOST}
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
