version: '3'
services:
  backend:
    build:
      context: ./backend
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - FRONTEND_HOST=${FRONTEND_HOST}
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
